import { SITE_URL } from '@/utils/api';

export default function robots() {
  return {
    rules: [
      {
        userAgent: '*',
        disallow: [
          // --- Hack-injected URL patterns ---
          '/wp-*.php',
          '/ctg/',
          '/products/',
          '/*ctgItemCd*',
          '/*similarImageSearchResultView*',
          '/*%DLINK*',
          // --- Pirated software / crack spam ---
          '/*crack*',
          '/*keygen*',
          '/*activator*',
          '/*portable*',
          '/*filehippo*',
          '/*filecr*',
          '/*no-virus*',
          '/*lifetime-full*',
          '/*x86x64*',
          '/*x32x64*',
          '/*gdrive*',
          '/*mediafire*',
          '/*resetters*',
          '/category/resetters/',
          // --- Specific known spam pages ---
          '/adobe-after-effects-portable-for-pc-all-versions-x32-x64-finalfilehippo/',
          '/adobe-premiere-pro-2025-crack-exe-windows-11-windows-11-2025/',
          '/anydesk-2024-portable-keygen-full-clean-tested/',
          '/anydesk-professional-portable-for-pc-no-virus-x32x64-latest-genuine/',
          '/artmoney-se-pro-crack-windows-x32-x64-latest-mediafire/',
          '/ashampoo-winoptimizer-crack-activator-clean-x86x64-windows-filecr/',
          '/easeus-data-recovery-crack-only-clean-x86-x64-lifetime-premium/',
          '/edrawings-portable-only-full-lifetime-verified/',
          '/filmora-portable-tool-full-lifetime-reddit/',
          '/jscreenfix-deluxe-crack-only-lifetime-full-2024/',
          '/matlab-portable-for-pc-no-virus-windows-10-ultimate/',
          '/matlab-r2023b-crack-exe-windows-lifetime-gdrive/',
          '/office-365-full-activated-100-worked-x32x64-100-worked-filehippo/',
          '/sketchup-portable-activator-latest-x86-x64-100-worked/',
          '/smartftp-enterprise-crack-portable-100-worked-x32-x64-latest-tested/',
          '/vegas-pro-crack-activator-full-no-virus-2025/',
          '/vegas-pro-portable-license-key-full-x64-final/',
          '/winhex-crack-only-no-virus-x86-x64-no-virus-bypass/',
          // --- WordPress hardening ---
          '/wp-admin/',
          '/wp-login.php',
          '/wp-register.php',
          '/wp-cron.php',
          '/wp-trackback.php',
          '/wp-links-opml.php',
          '/xmlrpc.php',
          // --- Low-value WP URLs ---
          '/feed/',
          '/comments/feed/',
          '/*/feed/',
          '/*/feed/rss/',
          '/*/feed/rss2/',
          '/*/feed/atom/',
          '/*?s=',
          '/*?p=',
          '/*?page_id=',
          '/*?attachment_id=',
          '/*?replytocom=',
          '/*?preview=',
          '/*?author=',
          '/*?paged=',
          '/tag/',
          '/author/',
        ],
        allow: [
          // --- Important rendering assets + real content ---
          '/wp-admin/admin-ajax.php',
          '/wp-content/uploads/',
          '/wp-content/themes/',
          '/*.css',
          '/*.js',
          '/*.png',
          '/*.jpg',
          '/*.jpeg',
          '/*.webp',
          '/*.svg',
          '/services/',
          '/rt-portfolios/',
          '/case-study/',
          '/about/',
          '/contact/',
          '/blog/',
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}